import { timingSafeEqual } from 'crypto'
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'

export const dynamic = 'force-dynamic'

// Standard portal-metrics endpoint consumed by the MD portal (EmploLink).
// GET /api/portal-metrics?from=YYYY-MM-DD&to=YYYY-MM-DD
// Auth: Authorization: Bearer <PORTAL_METRICS_SECRET> — a static secret
// generated by the portal when this app is registered (unlike the
// daily-rotating key used by /api/v1). Response shape: contract v1
// (see the portal's docs/METRICS_ENDPOINT_SPEC.md).

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/

function isAuthorized(req: NextRequest): boolean {
  const secret = process.env.PORTAL_METRICS_SECRET
  if (!secret) return false
  const header = req.headers.get('authorization') ?? ''
  if (!header.startsWith('Bearer ')) return false
  const candidate = Buffer.from(header.slice(7))
  const expected = Buffer.from(secret)
  if (candidate.length !== expected.length) return false
  return timingSafeEqual(candidate, expected)
}

// --- Scoring (ported from the portal's previous direct-DB implementation) ---

const SCORE_WEIGHTS = { completion: 0.45, throughput: 0.3, lowOpen: 0.25 }

function clamp01(n: number): number {
  return Math.max(0, Math.min(1, n))
}

type MetricRow = {
  email: string
  name: string
  handled: number
  completed: number
  reminders: number
  open_items: number
  high_prio: number
}

function scoreEngineers(rows: MetricRow[]) {
  const maxHandled = Math.max(1, ...rows.map((r) => r.handled))
  return rows.map((r) => {
    const completionRate = r.handled > 0 ? r.completed / r.handled : 0
    const openRatio = r.handled > 0 ? r.open_items / r.handled : 0
    const throughputNorm = clamp01(r.handled / maxHandled)
    const score = Math.round(
      100 *
        (SCORE_WEIGHTS.completion * completionRate +
          SCORE_WEIGHTS.throughput * throughputNorm +
          SCORE_WEIGHTS.lowOpen * (1 - openRatio))
    )
    return { ...r, completionRate, openRatio, score }
  })
}

// Status labels/colors as the portal used to render them.
const STATUS_META: Record<string, { label: string; color: string }> = {
  OSC_UPDATED: { label: 'Updated', color: '#10b981' },
  EMAIL_SENT: { label: 'Email sent', color: '#0ea5e9' },
  EMAIL_SENT_REMINDER: { label: 'Reminder', color: '#f59e0b' },
  CHECK_REMARKS: { label: 'Check remarks', color: '#8b5cf6' },
  ON_HOLD: { label: 'On hold', color: '#94a3b8' },
}

export async function GET(req: NextRequest) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const from = req.nextUrl.searchParams.get('from')
  const to = req.nextUrl.searchParams.get('to')
  if (!from || !to || !DATE_RE.test(from) || !DATE_RE.test(to)) {
    return NextResponse.json(
      { error: 'from and to (YYYY-MM-DD) are required' },
      { status: 400 }
    )
  }
  const fromDate = new Date(`${from}T00:00:00.000Z`)
  const toDate = new Date(`${to}T23:59:59.999Z`)

  // Per engineer (createdById), window on mailSentDate; open items are a
  // point-in-time snapshot (same queries the portal previously ran directly
  // against this database).
  const [metricsRaw, statusRaw, timelineRaw] = await Promise.all([
    prisma.$queryRaw<MetricRow[]>`
      SELECT u.email, u.name,
        count(*) FILTER (WHERE r."mailSentDate" BETWEEN ${fromDate} AND ${toDate})::int AS handled,
        count(*) FILTER (WHERE r."mailSentDate" BETWEEN ${fromDate} AND ${toDate} AND r.status = 'OSC_UPDATED')::int AS completed,
        count(*) FILTER (WHERE r."mailSentDate" BETWEEN ${fromDate} AND ${toDate} AND r.status = 'EMAIL_SENT_REMINDER')::int AS reminders,
        count(*) FILTER (WHERE r.status IN ('ON_HOLD','CHECK_REMARKS'))::int AS open_items,
        count(*) FILTER (WHERE r."mailSentDate" BETWEEN ${fromDate} AND ${toDate} AND r.priority = 'HIGH_PRIO')::int AS high_prio
      FROM "User" u
      LEFT JOIN "OscRequest" r ON r."createdById" = u.id
      WHERE u.role = 'SUPPORT_ENGINEER' AND u.active
      GROUP BY u.id, u.email, u.name
      ORDER BY handled DESC
    `,
    prisma.$queryRaw<{ status: string; count: number }[]>`
      SELECT status::text AS status, count(*)::int AS count
      FROM "OscRequest"
      WHERE "mailSentDate" BETWEEN ${fromDate} AND ${toDate}
      GROUP BY status
      ORDER BY count DESC
    `,
    prisma.$queryRaw<{ date: string; count: number }[]>`
      SELECT to_char("mailSentDate" AT TIME ZONE 'UTC', 'YYYY-MM-DD') AS date, count(*)::int AS count
      FROM "OscRequest"
      WHERE "mailSentDate" BETWEEN ${fromDate} AND ${toDate}
      GROUP BY 1
      ORDER BY 1
    `,
  ])

  const scored = scoreEngineers(metricsRaw).sort((a, b) => b.score - a.score)

  // Team-level rollups (same formulas the portal used).
  const sum = (fn: (r: (typeof scored)[number]) => number) =>
    scored.reduce((acc, r) => acc + fn(r), 0)
  const handled = sum((r) => r.handled)
  const completed = sum((r) => r.completed)
  const teamScore = scored.length
    ? Math.round(sum((r) => r.score) / scored.length)
    : 0

  return NextResponse.json({
    version: 1,
    kpis: [
      { label: 'Handled', value: handled, format: 'number' },
      { label: 'Completed', value: completed, format: 'number' },
      {
        label: 'Completion rate',
        value: handled > 0 ? completed / handled : null,
        format: 'percent',
      },
      { label: 'Reminders', value: sum((r) => r.reminders), format: 'number' },
      { label: 'Open items', value: sum((r) => r.open_items), format: 'number' },
      { label: 'Team score', value: teamScore, format: 'score' },
    ],
    statusBreakdown: statusRaw.map((s) => ({
      status: s.status,
      label: STATUS_META[s.status]?.label,
      count: Number(s.count),
      color: STATUS_META[s.status]?.color,
    })),
    timelineLabel: 'Requests handled',
    timeline: timelineRaw.map((t) => ({ date: t.date, count: Number(t.count) })),
    people: scored.map((r) => ({
      email: r.email,
      name: r.name,
      metrics: [
        { label: 'Handled', value: r.handled, format: 'number' },
        { label: 'Completed', value: r.completed, format: 'number' },
        { label: 'Completion', value: r.handled > 0 ? r.completionRate : null, format: 'percent' },
        { label: 'Reminders', value: r.reminders, format: 'number' },
        { label: 'Open', value: r.open_items, format: 'number' },
        { label: 'High-prio', value: r.high_prio, format: 'number' },
      ],
      score: r.score,
    })),
  })
}
